[project]
name = "OSL-repo-extractor"
description = "GitHub repo mining utility"
version = "0.1"
authors = [
    { name = "Jacob M. Penney", email = "jacobmpenney@gmail.com" }
]

dependencies = [
    "Cerberus==1.3.4",
    "PyGithub==1.55"
]

[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"
